#!/usr/bin/env bash
# GAP-043 — THE GATE: 44-test H3 compliance battery against a live harness,
# wired into `make test` and CI (.github/workflows/test.yml).
#
# Self-contained by design (default mode):
#   * The harness is generated by `hermes-h3 scaffold --lang py` from THIS
#     repo's own templates (src/h3_shim/templates/py/) — no external repo
#     checkout (get-h3/sdk-go) is required.
#   * The default endpoint mirrors the loader config at
#     ~/.hermes/h3/config.yaml (default_harness -> endpoint: localhost:9191);
#     the harness binds a FREE port scanned from 9191 instead of blind-binding
#     the default, so a busy default port can never produce a false red.
#   * No new project dependencies: the scaffolded harness installs its own
#     requirements.txt into a throwaway venv under a mktemp workdir.
#
# External mode (H3_ENDPOINT set): run the battery against an already-running
# endpoint (e.g. a registered harness) without scaffolding — the classic
# `h3-test --endpoint` flow, with the same exit-0 + 44/44 assertions.
#
# FAILS the build (exit 1) when:
#   * h3-test exits non-zero — 1 = real compliance failure, 2 = unreachable /
#     not-an-H3-endpoint. Never swallowed, never silently green.
#   * The output does not assert TOTAL 44/44 PASSED.
#   * The harness never becomes healthy (curl /v1/health).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK_DIR="$(mktemp -d)"
PASSED=0
FAILED=0
SERVER_PID=""

cleanup() {
    if [ -n "$SERVER_PID" ]; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

pass() { echo "  ✅ PASS: $1"; PASSED=$((PASSED + 1)); }
fail() { echo "  ❌ FAIL: $1"; FAILED=$((FAILED + 1)); }

# Find a free TCP port starting at $1 (default 9191).
free_port() {
    python3 -c "
import socket, sys
start = int(sys.argv[1])
for port in range(start, start + 50):
    with socket.socket() as s:
        try:
            s.bind(('127.0.0.1', port))
        except OSError:
            continue
        print(port)
        sys.exit(0)
sys.exit(1)
" "$1"
}

# Resolve the h3-test CLI: repo venv first (CI/local make), then PATH.
if [ -x "$REPO_DIR/.venv/bin/h3-test" ]; then
    H3_TEST="$REPO_DIR/.venv/bin/h3-test"
    HERMES_H3="$REPO_DIR/.venv/bin/hermes-h3"
else
    H3_TEST="${H3_TEST:-$(command -v h3-test || true)}"
    HERMES_H3="${HERMES_H3:-$(command -v hermes-h3 || true)}"
fi
if [ -z "${H3_TEST:-}" ] || [ ! -x "$H3_TEST" ]; then
    echo "❌ FAIL: h3-test not found — install the shim first (make install / pip install -e '.[dev]')"
    exit 1
fi
if [ -z "${HERMES_H3:-}" ] || [ ! -x "$HERMES_H3" ]; then
    echo "❌ FAIL: hermes-h3 not found (sibling of h3-test in the same bin dir)"
    exit 1
fi

# The endpoint the loader config declares (informational default; the
# self-contained mode binds a free port, external mode uses H3_ENDPOINT).
configured_endpoint() {
    local cfg="${H3_CONFIG:-$HOME/.hermes/h3/config.yaml}"
    if [ -f "$cfg" ]; then
        local dh ep
        dh="$(sed -n 's/^default_harness:[[:space:]]*//p' "$cfg" | head -1 | tr -d ' \r')"
        if [ -n "$dh" ]; then
            ep="$(grep -A2 "^[[:space:]]*${dh}:" "$cfg" 2>/dev/null | grep 'endpoint:' | head -1 | sed 's/.*endpoint:[[:space:]]*//' | tr -d ' \r' || true)"
            if [ -n "$ep" ]; then
                echo "$ep"
                return
            fi
        fi
    fi
    echo "http://localhost:9191"
}

if [ -n "${H3_ENDPOINT:-}" ]; then
    # ── EXTERNAL MODE: battery against an already-running endpoint ──────────
    ENDPOINT="$H3_ENDPOINT"
    echo "=== H3 Compliance Battery Gate (GAP-043) — external endpoint ==="
    echo "Endpoint: $ENDPOINT (H3_ENDPOINT override)"
    echo "h3-test:  $H3_TEST"
    echo ""
else
    # ── SELF-CONTAINED MODE: scaffold harness, run battery against it ───────
    echo "=== H3 Compliance Battery Gate (GAP-043) ==="
    echo "Configured default endpoint: $(configured_endpoint) (from ~/.hermes/h3/config.yaml; H3_ENDPOINT overrides)"
    echo "h3-test:  $H3_TEST"
    echo "Work dir: $WORK_DIR"
    echo ""

    echo "── 1. Scaffolding harness (hermes-h3 scaffold --lang py)"
    SCAFFOLD_DIR="$WORK_DIR/scaffold"
    if ! "$HERMES_H3" scaffold --lang py --output-dir "$SCAFFOLD_DIR" --force > "$WORK_DIR/scaffold.log" 2>&1; then
        fail "hermes-h3 scaffold --lang py (see $WORK_DIR/scaffold.log)"
        exit 1
    fi
    HARNESS_DIR="$SCAFFOLD_DIR/h3-harness-py"
    if [ ! -f "$HARNESS_DIR/main.py" ]; then
        fail "scaffolded harness missing ($HARNESS_DIR/main.py)"
        exit 1
    fi
    pass "scaffolded harness: $HARNESS_DIR"

    echo "── 2. Installing harness deps (throwaway venv — no project deps touched)"
    if python3 -m venv "$WORK_DIR/venv" > /dev/null 2>&1 \
       && "$WORK_DIR/venv/bin/pip" install -q -r "$HARNESS_DIR/requirements.txt" > /dev/null 2>&1; then
        pass "harness venv ready (fastapi/uvicorn/pydantic from requirements.txt)"
    else
        fail "harness venv install"
        exit 1
    fi

    echo "── 3. Starting harness"
    PORT="$(free_port 9191)" || { fail "no free port found"; exit 1; }
    (
        cd "$HARNESS_DIR"
        PORT="$PORT" exec "$WORK_DIR/venv/bin/python" main.py
    ) > "$WORK_DIR/harness.log" 2>&1 &
    SERVER_PID=$!

    HEALTH_OK=""
    for _ in {1..30}; do
        if curl -sf -o /dev/null "http://127.0.0.1:$PORT/v1/health"; then
            HEALTH_OK=1
            break
        fi
        sleep 1
    done
    if [ -z "$HEALTH_OK" ]; then
        fail "harness did not answer /v1/health on :$PORT (see harness.log)"
        exit 1
    fi
    pass "harness healthy on :$PORT (/v1/health)"

    ENDPOINT="http://127.0.0.1:$PORT"
fi

# ── Run THE GATE: battery must exit 0 AND print TOTAL 44/44 PASSED ───────────
echo "── 4. Running 44-test battery (h3-test --endpoint $ENDPOINT)"
set +e
"$H3_TEST" --endpoint "$ENDPOINT" > "$WORK_DIR/battery.log" 2>&1
BATTERY_CODE=$?
set -e
cat "$WORK_DIR/battery.log"
echo ""

if [ "$BATTERY_CODE" -ne 0 ]; then
    fail "h3-test exited $BATTERY_CODE (1=compliance failure, 2=unreachable/not-H3) — the gate FAILS the build"
else
    pass "h3-test exit code 0"
fi

if grep -q "TOTAL.*44/44.*PASSED" "$WORK_DIR/battery.log"; then
    pass "battery asserts TOTAL 44/44 PASSED"
else
    fail "battery output missing 'TOTAL 44/44 PASSED' — gate FAILS the build"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "=== Compliance Battery Gate Results ==="
echo "  Passed: $PASSED"
echo "  Failed: $FAILED"
echo ""

if [ "$FAILED" -gt 0 ]; then
    echo "❌ COMPLIANCE GATE FAILED"
    exit 1
else
    echo "✅ COMPLIANCE GATE PASSED — 44/44, exit 0"
    exit 0
fi
